### ISSUE TITLE
this framework support cross-platform?

### ISSUE THREAD

**Issue by krutitrivedi** [netguru/BlueSwift#18]
actually i want to develop bluetooth low energy where central application send data to peripheral and that peripheral app is on ios and android platform so is this possible using your library

**Comment by poszposz** [comment]
@krutitrivedi unfortunately not, this library supports iOS only, it won't work on Android. There is also no corresponding Android library available.
Closing this thread :)

**Comment by krutitrivedi** [comment]
so how can android and iOS device connect with same sensor? i understand that iOS scan and advertise in CBUUID format but i have doubt that how both OS connect with external hardware sensor
