### ISSUE TITLE
can i measure distance from central to peripheral?

### ISSUE THREAD

**Issue by krutitrivedi** [netguru/BlueSwift#20]

**Comment by poszposz** [comment]
Unfortunately you can't do this in any easy way. It could be possible by discovering the peripherals and passing false via `advertisementValidationHandler` so the device won't connect. However this closure currently does not pass the `CBPeripheral` instance to be able to extract RSSI value from it.
If you want that, I can include this in next release and post it in few days from now :) 
However RSSI does won't give you any exact information about distance, it's just received signal strength so you would have to calibrate it properly on each device the library will be used. Also it's in logarithmic scale so you would have to calculate it to meters. You can find a simple tutorial here: https://iotandelectronics.wordpress.com/2016/10/07/how-to-calculate-distance-from-the-rssi-value-of-the-ble-beacon/
Last but not least, please have in mind that without some complicated math, your results won't be exact and you can not rely on them. You can just specify if you are near or far from the device.

Please let me know if I can help in any other way after that clarification! ;)

**Comment by krutitrivedi** [comment]
yes, if you reales version with distance measurement it is better

**Comment by Siemian** [comment]
Unfortunately this feature is no longer on our roadmap. Please feel free to submit the PR.
