### ISSUE TITLE
Possible issue

### ISSUE THREAD

**Issue by kanstantsin-bucha** [netguru/BlueSwift#39]
Hi!

I installed library using cocoapods. It is not compiled

place `internal extension AdvertisementData `

method `internal var data: Any? {`

```
  case .servicesUUIDs(let uuid):
            return try? [CBUUID(uuidString: uuid)] -> Maybe [try? CBUUID(uuidString: uuid)] 
```

With best wishes

**Comment by Siemian** [comment]
Could you try the newest version?
